export const DSA_TOPICS = [
  'Array',
  'String',
  'Hash Table',
  'Math',
  'Dynamic Programming',
  'Sorting',
  'Greedy',
  'Depth-First Search',
  'Binary Search',
  'Breadth-First Search',
  'Tree',
  'Matrix',
  'Bit Manipulation',
  'Two Pointers',
  'Stack',
  'Heap (Priority Queue)',
  'Graph',
  'Linked List',
  'Sliding Window',
  'Backtracking',
  'Divide and Conquer',
  'Union Find',
  'Trie',
  'Monotonic Stack',
  'Recursion',
  'Binary Tree',
  'Binary Search Tree',
  'Queue',
  'Segment Tree',
  'Topological Sort',
] as const;

export type DSATopic = (typeof DSA_TOPICS)[number];
